#!/usr/bin/env python3
"""Sage quotient exporter for finite Coxeter subgroup/coset data.

The script is intentionally narrow and deterministic.  When run inside Sage it
enumerates a finite Coxeter group with Sage algebraic-real reflection matrices,
enumerates the subgroup generated by the requested words, builds left cosets
``H\\W`` with right multiplication by Coxeter generators, and emits the
``QuotientComplex`` JSON used by the app.  When Sage is not importable it emits
a skipped-status artifact instead of pretending an external certificate exists.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))

from sage_export_backend import (
    build_reflection_matrices,
    sage_imports,
    stable_path_label,
)


BACKEND_ID = "sageQuotientExportBackend"
BACKEND_VERSION = "2.0.0"
CHECKED_AT = "1970-01-01T00:00:00.000Z"
MAX_GROUP_ELEMENTS = 50_000
DEFAULT_MAX_COSETS = 256


def print_json(value: dict[str, Any]) -> None:
    print(json.dumps(value, indent=2, sort_keys=True))


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf8")).hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError("input JSON must be an object")
    return value


def sage_runtime_status() -> dict[str, Any]:
    try:
        import sage.all  # type: ignore  # noqa: F401
    except Exception as exc:  # pragma: no cover - local tool dependent
        return {
            "ok": False,
            "status": "skipped",
            "backend": BACKEND_ID,
            "backendVersion": BACKEND_VERSION,
            "requiredRuntime": "SageMath",
            "checkedAt": CHECKED_AT,
            "warnings": [
                "SageMath is not importable in this Python runtime; native Sage quotient enumeration was skipped."
            ],
            "detail": str(exc),
        }

    return {
        "ok": True,
        "status": "available",
        "backend": BACKEND_ID,
        "backendVersion": BACKEND_VERSION,
        "requiredRuntime": "SageMath",
        "checkedAt": CHECKED_AT,
    }


def skipped_report(input_path: Path | None, input_text: str) -> dict[str, Any]:
    status = sage_runtime_status()
    return {
        "ok": True,
        "status": "skipped",
        "backend": BACKEND_ID,
        "backendVersion": BACKEND_VERSION,
        "checkedAt": CHECKED_AT,
        "inputPath": stable_path_label(input_path) if input_path else None,
        "inputHash": sha256_text(input_text),
        "warnings": status["warnings"],
    }


def is_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def validate_request(request: dict[str, Any]) -> dict[str, Any]:
    errors: list[str] = []
    source = request.get("sourceSystem")
    if not isinstance(source, dict):
        errors.append("sourceSystem must be an object")
    else:
        rank = source.get("rank")
        matrix = source.get("coxeterMatrix")
        generators = source.get("generators")
        if source.get("schemaVersion") != 1:
            errors.append("sourceSystem.schemaVersion must be 1")
        if not is_int(rank) or rank < 1:
            errors.append("sourceSystem.rank must be a positive integer")
        if not isinstance(generators, list) or len(generators) != rank:
            errors.append("sourceSystem.generators must have rank entries")
        if not isinstance(matrix, list) or len(matrix) != rank:
            errors.append("sourceSystem.coxeterMatrix must be rank by rank")
        elif is_int(rank):
            for i, row in enumerate(matrix):
                if not isinstance(row, list) or len(row) != rank:
                    errors.append(f"sourceSystem.coxeterMatrix[{i}] must have rank entries")
                    continue
                for j, entry in enumerate(row):
                    if i == j:
                        if entry != 1:
                            errors.append(f"sourceSystem.coxeterMatrix[{i}][{j}] must be 1")
                    elif entry != "inf" and (not is_int(entry) or entry < 2):
                        errors.append(
                            f"sourceSystem.coxeterMatrix[{i}][{j}] must be an integer >= 2 or 'inf'"
                        )
                    elif isinstance(matrix[j], list) and matrix[j][i] != entry:
                        errors.append(f"sourceSystem.coxeterMatrix must be symmetric at ({i}, {j})")

    subgroup_words = request.get("subgroupGenerators")
    if not isinstance(subgroup_words, list):
        errors.append("subgroupGenerators must be an array of words")
    else:
        rank = source.get("rank") if isinstance(source, dict) else None
        for word_index, word in enumerate(subgroup_words):
            if not isinstance(word, list):
                errors.append(f"subgroupGenerators[{word_index}] must be a word array")
                continue
            for letter_index, generator in enumerate(word):
                if (
                    not is_int(generator)
                    or generator < 0
                    or (is_int(rank) and generator >= rank)
                ):
                    errors.append(
                        f"subgroupGenerators[{word_index}][{letter_index}] must be a valid generator index"
                    )

    max_cosets = request.get("maxCosets", DEFAULT_MAX_COSETS)
    if not is_int(max_cosets) or max_cosets < 1:
        errors.append("maxCosets must be a positive integer when provided")

    if errors:
        raise ValueError("; ".join(errors))
    return source


def matrix_tuple_key(matrix_value: Any) -> tuple[Any, ...]:
    return tuple(matrix_value.list())


def identity_matrix_for(rank: int) -> Any:
    from sage.all import AA, identity_matrix  # type: ignore

    return identity_matrix(AA, rank)


def multiply(left: Any, right: Any) -> Any:
    return left * right


def node_id_from_word(word: list[int]) -> str:
    return "e" if not word else f"w:{'.'.join(str(item) for item in word)}"


def edge_id(source: str, target: str, generator: int) -> str:
    return (
        f"qe:{source}:s{generator}"
        if source == target
        else f"qe:{source}:{target}:s{generator}"
    )


def finite_pairs(matrix: list[list[Any]]) -> list[tuple[int, int, int]]:
    pairs: list[tuple[int, int, int]] = []
    for i in range(len(matrix)):
        for j in range(i + 1, len(matrix)):
            entry = matrix[i][j]
            if is_int(entry):
                pairs.append((i, j, entry))
    return pairs


def canonical_boundary_key(boundary: list[str]) -> str:
    rotations: list[str] = []
    for index in range(len(boundary)):
        rotations.append(">".join(boundary[index:] + boundary[:index]))
    reversed_boundary = list(reversed(boundary))
    for index in range(len(reversed_boundary)):
        rotations.append(
            ">".join(reversed_boundary[index:] + reversed_boundary[:index])
        )
    return sorted(rotations)[0] if rotations else ""


def word_matrix(word: list[int], reflections: list[Any]) -> Any:
    matrix = identity_matrix_for(len(reflections))
    for generator in word:
        matrix = multiply(matrix, reflections[generator])
    return matrix


def enumerate_finite_group(source: dict[str, Any], reflections: list[Any]) -> dict[str, Any]:
    identity = identity_matrix_for(source["rank"])
    elements = [
        {
            "id": "e",
            "word": [],
            "matrix": identity,
            "key": matrix_tuple_key(identity),
        }
    ]
    key_to_index = {elements[0]["key"]: 0}
    capped = False

    cursor = 0
    while cursor < len(elements):
        element = elements[cursor]
        cursor += 1
        for generator, reflection in enumerate(reflections):
            matrix = multiply(element["matrix"], reflection)
            key = matrix_tuple_key(matrix)
            if key in key_to_index:
                continue
            if len(elements) >= MAX_GROUP_ELEMENTS:
                capped = True
                continue
            word = [*element["word"], generator]
            key_to_index[key] = len(elements)
            elements.append(
                {
                    "id": node_id_from_word(word),
                    "word": word,
                    "matrix": matrix,
                    "key": key,
                }
            )

    return {"elements": elements, "keyToIndex": key_to_index, "capped": capped}


def enumerate_subgroup(
    request: dict[str, Any],
    reflections: list[Any],
    group: dict[str, Any],
) -> dict[str, Any]:
    subgroup_matrices: list[Any] = []
    for word in request.get("subgroupGenerators", []):
        subgroup_matrices.append(word_matrix(word, reflections))
        subgroup_matrices.append(word_matrix(list(reversed(word)), reflections))

    identity = identity_matrix_for(len(reflections))
    elements = [{"matrix": identity, "key": matrix_tuple_key(identity), "word": []}]
    seen = {elements[0]["key"]}
    errors: list[str] = []
    capped = False

    cursor = 0
    while cursor < len(elements):
        if not subgroup_matrices:
            break
        element = elements[cursor]
        cursor += 1
        for generator_matrix in subgroup_matrices:
            matrix = multiply(element["matrix"], generator_matrix)
            key = matrix_tuple_key(matrix)
            if key not in group["keyToIndex"]:
                errors.append(
                    "subgroup enumeration reached an element outside the enumerated finite group"
                )
                continue
            if key in seen:
                continue
            if len(elements) >= MAX_GROUP_ELEMENTS:
                capped = True
                continue
            seen.add(key)
            elements.append({"matrix": matrix, "key": key, "word": []})

    return {"elements": elements, "keys": sorted(str(key) for key in seen), "errors": errors, "capped": capped}


def build_left_cosets(group: dict[str, Any], subgroup: dict[str, Any]) -> dict[str, Any]:
    element_coset = [-1 for _ in group["elements"]]
    cosets: list[dict[str, Any]] = []
    errors: list[str] = []

    for index, representative in enumerate(group["elements"]):
        if element_coset[index] >= 0:
            continue
        member_indices: set[int] = set()
        for subgroup_element in subgroup["elements"]:
            matrix = multiply(subgroup_element["matrix"], representative["matrix"])
            key = matrix_tuple_key(matrix)
            member_index = group["keyToIndex"].get(key)
            if member_index is None:
                errors.append("left-coset construction found an element outside the enumerated group")
                continue
            member_indices.add(member_index)
        coset_index = len(cosets)
        for member_index in member_indices:
            if element_coset[member_index] not in (-1, coset_index):
                errors.append("left-coset construction produced overlapping cosets")
            element_coset[member_index] = coset_index
        cosets.append(
            {
                "id": f"q{coset_index}",
                "representativeIndex": index,
                "memberIndices": sorted(member_indices),
            }
        )

    return {"cosets": cosets, "elementCoset": element_coset, "errors": errors}


def attach_game(request: dict[str, Any], source: dict[str, Any], input_hash: str) -> dict[str, Any] | None:
    preset = request.get("includeGamePreset")
    if preset == "i2-5-height":
        return {
            "activeAssignmentId": "i2-5-height-generators",
            "activeCocycleId": "i2-5-height-cocycle",
            "assignments": [
                {
                    "id": "i2-5-height-generators",
                    "label": "I2(5) height cocycle s0=+1, s1=-1",
                    "description": "Integer generator labeling used by the quotient/game demo.",
                    "kind": "integer-generator-labeling",
                    "generatorStates": [
                        {"generator": 0, "value": 1},
                        {"generator": 1, "value": -1},
                    ],
                    "notes": [
                        "For the identity-subgroup I2(5) quotient, the alternating decagon has zero boundary sum."
                    ],
                }
            ],
            "cocycles": [
                {
                    "id": "i2-5-height-cocycle",
                    "label": "I2(5) demo cocycle",
                    "assignmentId": "i2-5-height-generators",
                    "coefficientRing": "Z",
                    "certificate": {
                        "status": "passed",
                        "backend": BACKEND_ID,
                        "scopes": ["morse-cocycle"],
                        "inputHash": input_hash,
                    },
                    "notes": [
                        "The app and certifier scripts re-check the rank-two boundary sums before treating this as passed."
                    ],
                }
            ],
            "experimentLogs": [
                {
                    "id": "i2-5-workflow-demo",
                    "label": "I2(5) quotient/game demo",
                    "inputHash": input_hash,
                    "assignmentId": "i2-5-height-generators",
                    "cocycleId": "i2-5-height-cocycle",
                    "diagnostics": {
                        "intendedLenses": [
                            "ascending-link",
                            "descending-link",
                            "full-local-link",
                        ]
                    },
                }
            ],
            "notes": [
                "This block is a demo game assignment, not a torsion-free or manifold certificate."
            ],
        }
    if preset == "zero":
        return {
            "activeAssignmentId": "zero-generators",
            "activeCocycleId": "zero-cocycle",
            "assignments": [
                {
                    "id": "zero-generators",
                    "label": "Zero generator labels",
                    "kind": "integer-generator-labeling",
                    "generatorStates": [
                        {"generator": generator, "value": 0}
                        for generator in range(source["rank"])
                    ],
                }
            ],
            "cocycles": [
                {
                    "id": "zero-cocycle",
                    "label": "Zero cocycle",
                    "assignmentId": "zero-generators",
                    "coefficientRing": "Z",
                }
            ],
        }
    return None


def build_quotient_complex(
    request: dict[str, Any],
    source: dict[str, Any],
    input_hash: str,
) -> dict[str, Any]:
    if any(entry == "inf" for row in source["coxeterMatrix"] for entry in row):
        return {
            "ok": True,
            "status": "skipped",
            "backend": BACKEND_ID,
            "backendVersion": BACKEND_VERSION,
            "checkedAt": CHECKED_AT,
            "inputHash": input_hash,
            "warnings": [
                "Native Sage quotient export in this app currently supports finite Coxeter systems. Infinite finite-index subgroup enumeration needs a separate certified Sage task."
            ],
        }

    reflections = build_reflection_matrices(source, sage_imports())
    group = enumerate_finite_group(source, reflections)
    subgroup = enumerate_subgroup(request, reflections, group)
    coset_data = build_left_cosets(group, subgroup)
    errors = [
        *(["finite group enumeration hit the element cap"] if group["capped"] else []),
        *(["subgroup enumeration hit the element cap"] if subgroup["capped"] else []),
        *subgroup["errors"],
        *coset_data["errors"],
    ]
    max_cosets = request.get("maxCosets", DEFAULT_MAX_COSETS)
    if len(coset_data["cosets"]) > max_cosets:
        errors.append(
            f"quotient has {len(coset_data['cosets'])} cosets, exceeding maxCosets {max_cosets}"
        )
    if errors:
        raise ValueError("; ".join(errors))

    vertices = []
    for coset in coset_data["cosets"]:
        representative = group["elements"][coset["representativeIndex"]]
        vertices.append(
            {
                "id": coset["id"],
                "label": coset["id"],
                "representativeWord": representative["word"],
                "sourceNodeIds": [group["elements"][index]["id"] for index in coset["memberIndices"]],
            }
        )

    action_images_by_generator: list[dict[str, str]] = []
    actions = []
    for generator, reflection in enumerate(reflections):
        images: dict[str, str] = {}
        for coset in coset_data["cosets"]:
            representative = group["elements"][coset["representativeIndex"]]
            target_matrix = multiply(representative["matrix"], reflection)
            target_element = group["keyToIndex"].get(matrix_tuple_key(target_matrix))
            if target_element is None:
                raise ValueError(f"generator {generator} action left the enumerated group")
            target_coset = coset_data["elementCoset"][target_element]
            if target_coset < 0:
                raise ValueError(f"generator {generator} action left the enumerated quotient at {coset['id']}")
            images[coset["id"]] = coset_data["cosets"][target_coset]["id"]
        action_images_by_generator.append(images)
        actions.append({"generator": generator, "images": images})

    edges = []
    for coset in coset_data["cosets"]:
        for generator in range(source["rank"]):
            target = action_images_by_generator[generator][coset["id"]]
            edges.append(
                {
                    "id": edge_id(coset["id"], target, generator),
                    "source": coset["id"],
                    "target": target,
                    "generator": generator,
                    "inverseEdgeId": edge_id(target, coset["id"], generator),
                    "label": source["generators"][generator].get("label", f"s{generator}"),
                }
            )

    cells = []
    seen_cells: set[str] = set()
    for i, j, m in finite_pairs(source["coxeterMatrix"]):
        for vertex in vertices:
            boundary_vertices: list[str] = []
            boundary_edges: list[str] = []
            current = vertex["id"]
            for step in range(2 * m):
                generator = i if step % 2 == 0 else j
                target = action_images_by_generator[generator][current]
                boundary_vertices.append(current)
                boundary_edges.append(edge_id(current, target, generator))
                current = target
            if current != vertex["id"]:
                raise ValueError(f"rank-two relation ({i}, {j}) did not close at {vertex['id']}")
            key = f"{i}-{j}:{canonical_boundary_key(boundary_vertices)}"
            if key in seen_cells:
                continue
            seen_cells.add(key)
            cells.append(
                {
                    "id": f"qcell:{i}-{j}:{len(cells)}",
                    "generatorPair": [i, j],
                    "m": m,
                    "boundaryVertexIds": boundary_vertices,
                    "boundaryEdgeIds": boundary_edges,
                }
            )

    warning = (
        "Quotient was produced by native Sage finite left-coset enumeration from the request file. "
        "Infinite or large-index subgroup enumeration requires a separate Sage/GAP certificate."
    )
    certificate = {
        "status": "passed",
        "backend": BACKEND_ID,
        "backendVersion": BACKEND_VERSION,
        "scopes": ["quotient-action"],
        "command": "sage -c runpy.run_path('scripts/sage_quotient_export.py') --input <request>",
        "checkedAt": CHECKED_AT,
        "inputHash": input_hash,
        "diagnostics": {
            "groupElements": len(group["elements"]),
            "subgroupElements": len(subgroup["elements"]),
            "cosets": len(vertices),
            "finitePairCells": len(cells),
            "cosetConvention": "left cosets H\\W with right multiplication by Coxeter generators",
            "deduplication": "sage algebraic-real reflection matrix keys",
        },
        "warnings": [warning],
    }

    quotient: dict[str, Any] = {
        "schemaVersion": 1,
        "name": (
            f"{source['name']} quotient ({request.get('subgroupName')})"
            if request.get("subgroupName")
            else f"{source['name']} quotient from build request"
        ),
        "sourceSystem": source,
        "generatorRank": source["rank"],
        "permutationAction": actions,
        "vertices": vertices,
        "edges": edges,
        "twoCells": cells,
        "subgroup": {
            "name": request.get("subgroupName", "request subgroup"),
            "index": len(vertices),
            "generators": request.get("subgroupGenerators", []),
            "source": BACKEND_ID,
            "certificate": certificate,
            "notes": request.get("notes", []),
        },
        "verifier": certificate,
        "schreierCertificate": {
            "status": "passed",
            "method": "external-sage",
            "checkedAt": CHECKED_AT,
            "generatorRank": source["rank"],
            "vertexCount": len(vertices),
            "checks": {
                "generatorRegularity": True,
                "bijectiveActions": True,
                "involutiveGenerators": True,
                "edgeCompatibility": True,
                "coxeterRelations": True,
                "rankTwoCellCoverage": True,
                "duplicateRankTwoCells": True,
            },
            "rankTwoOrbits": [
                {
                    "generatorPair": cell["generatorPair"],
                    "m": cell["m"],
                    "orbitKey": f"{','.join(str(item) for item in cell['generatorPair'])}:{'>'.join(cell['boundaryVertexIds'])}",
                    "boundaryVertexIds": cell["boundaryVertexIds"],
                    "matchedCellIds": [cell["id"]],
                }
                for cell in cells
            ],
            "errors": [],
            "warnings": [warning],
        },
        "warnings": [warning],
    }
    game = attach_game(request, source, input_hash)
    if game:
        quotient["game"] = game

    hash_source = json.dumps(quotient, sort_keys=True, separators=(",", ":"))
    output_hash = sha256_text(hash_source)
    quotient["verifier"]["outputHash"] = output_hash
    quotient["subgroup"]["certificate"]["outputHash"] = output_hash
    if quotient.get("game", {}).get("cocycles"):
        certificate_block = quotient["game"]["cocycles"][0].get("certificate")
        if certificate_block:
            certificate_block["outputHash"] = output_hash

    return quotient


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--check-runtime", action="store_true")
    args = parser.parse_args()

    if args.check_runtime:
        print_json(sage_runtime_status())
        return 0

    input_text = args.input.read_text(encoding="utf8") if args.input else "{}"
    if sage_runtime_status()["ok"] is not True:
        report = skipped_report(args.input, input_text)
        text = json.dumps(report, indent=2, sort_keys=True) + "\n"
        if args.output:
            args.output.write_text(text, encoding="utf8")
        else:
            print(text, end="")
        return 0

    if args.input is None:
        parser.error("--input is required for quotient export")

    try:
        request = load_json(args.input)
        source = validate_request(request)
        result = build_quotient_complex(request, source, sha256_text(input_text))
    except Exception as exc:
        print_json(
            {
                "ok": False,
                "status": "failed",
                "backend": BACKEND_ID,
                "backendVersion": BACKEND_VERSION,
                "checkedAt": CHECKED_AT,
                "inputPath": stable_path_label(args.input),
                "inputHash": sha256_text(input_text),
                "errors": [str(exc)],
            }
        )
        return 1

    text = json.dumps(result, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.write_text(text, encoding="utf8")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
